package com.ch1kkgq;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class V1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void v1() {
    driver.get("https://demo.guru99.com/V4/");
    driver.manage().window().setSize(new Dimension(974, 860));
    driver.findElement(By.name("uid")).click();
    driver.findElement(By.name("uid")).sendKeys("mngr577301");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("hyjasUh");
    driver.findElement(By.name("uid")).click();
    {
      String value = driver.findElement(By.name("uid")).getAttribute("value");
      assertThat(value, is("mngr577301"));
    }
    driver.findElement(By.name("btnLogin")).click();
    driver.findElement(By.cssSelector(".heading3 > td")).click();
    assertThat(driver.findElement(By.cssSelector(".heading3 > td")).getText(), is("Manger Id : mngr577301"));
    driver.findElement(By.cssSelector(".heading3:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".heading3:nth-child(1)")).getText(), is("Welcome To Manager\\\'s Page of Guru99 Bank"));
  }
}
